# Config v5.4 | Join-Login: FULL, HIDDEN, PERMISSION_RANGE, DISABLED

# Unterstütze Sprachen: DE (Deutsch), EN (Englisch) -> Bei Änderung bitte "messages.yml" löschen und Server neustarten/laden.
# Supported languages: EN (English), DE (German) -> If you change please delete "messages.yml" and restart or reload server.
language: DE

# Bestimmt die Art, wie ein Supporter beim betreten des Servers eingeloggt werden soll.
# FULL -> Jeder Supporter wird automatisch beim betreten des Servers eingeloggt.
# HIDDEN -> Jeder Supporter wird automatisch beim betreten des Servers versteckt eingeloggt.
# PERMISSION_RANGE -> Jeder Supporter wird nach seiner höchstrangigsten Permission eingeloggt.
# DISABLED -> Deaktiviert
#
# Defines the way a supporter should be logged in when joining the server.
# FULL -> Automatic normal login.
# HIDDEN -> Automatic hidden login.
# PERMISSION_RANGE -> Automatic login according to highest permission.
# DISABLED -> disabled
join-login: DISABLED

# Aktiviert oder deaktiviert den Updater, welcher beim Pluginstart in der Konsole ausgeführt wird.
# Enables or     disables the console-updater.
# (true)         (false)
check-update: true
